---
dist: trusty
language: node_js
node_js: 7
env: PHANTOMJS_EXECUTABLE=node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs CHROME_PATH=google-chrome-beta
before_script:
  - npm run build-tests
  - npm run serve-tests &
addons:
  chrome: beta
